export const environment = {
    production:false,
    staffLoginUrl:'http://localhost:8080/api/staff/authenticate',
    getCustomerStatement:'http://localhost:8080/api/staff/customer/getAccountStatmentById',
    listAccountToBeApproved:'http://localhost:8080/api/staff/customer/getAllAccountToBeApproved',
    approveAccount:'http://localhost:8080/api/staff/customer/approveAccountOrNot',
    listAllCustomer:'http://localhost:8080/api/staff/customer/listAllCustomer',
    EnableOrDisableCustomer:'http://localhost:8080/api/staff/customer/changeCustomerStatus',
    listBanToBeApproved:'http://localhost:8080/api/staff/customer/listBeneficiaryToBeApproved',
    approveban:'http://localhost:8080/api/staff/customer/approveBeneficiaryOrNot',
    adminLoginUrl:'http://localhost:8080/api/admin/authenticate',
    createStaff:'http://localhost:8080/api/admin/createstaff',
    listAllStaff:'http://localhost:8080/api/admin/listAllStaff',
    enableStaff:'http://localhost:8080/api/admin/EnableOrDisableStaff',
    staffTransfer:'http://localhost:8080/transfers/make',
    listTransfer:'http://localhost:8080/transfers/listAllTransfers',
};